#default url : localhost:port
server:
  port: 8090
#  contextPath: /orm

spring: 
  application: 
    name: Demo project
  mvc: 
    view: 
      prefix: /WEB-INF/views/
      suffix: .jsp

project:
    page:
      index: index

mybatis:
  type-aliases-package: com.ntut.practice.demo.entity
  mapper-locations: classpath:mapper/*.xml

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/orm
  connectionProperties: useSSL=true;useUnicode=yes;characterEncoding=utf8
  userName: admin
  password: 1a2b