#default url : localhost:port
server:
  port: 8090
      
spring: 
  application: 
    name: Demo project
  mvc: 
    view: 
      prefix: /WEB-INF/views/
      suffix: .html

project:
    page:
      index: index

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/orm
  connectionProperties: useSSL=true;useUnicode=yes;characterEncoding=utf8
  userName: admin
  password: 1a2b